# Generated by Django 3.2.15 on 2024-02-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0012_alter_application_dietary_restrictions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="dietary_restrictions",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("none", "None"),
                    ("halal", "Halal"),
                    ("vegetarian", "Vegetarian"),
                    ("vegan", "Vegan"),
                    ("celiac-disease", "Celiac Disease"),
                    ("allergies", "Allergies"),
                    ("kosher", "Kosher"),
                    ("gluten-Free", "Gluten-free"),
                    ("other-specify", "Other (please specify)"),
                ],
                max_length=50,
            ),
        ),
    ]
