# Generated by Django 3.2.15 on 2024-02-24 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_alter_application_dietary_restrictions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='email_agree',
        ),
        migrations.RemoveField(
            model_name='application',
            name='how_many_hackathons',
        ),
        migrations.RemoveField(
            model_name='application',
            name='logistics_agree',
        ),
        migrations.RemoveField(
            model_name='application',
            name='school',
        ),
        migrations.RemoveField(
            model_name='application',
            name='tshirt_size',
        ),
        migrations.RemoveField(
            model_name='application',
            name='what_hackathon_experience',
        ),
        migrations.AddField(
            model_name='application',
            name='apt_number',
            field=models.CharField(blank=True, help_text='e.g. Apt. No. 13', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='postal_code',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='region',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='specific_dietary_requirement',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='street_address',
            field=models.CharField(default='', help_text='e.g. 35 St George St', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='student_number',
            field=models.CharField(default=1008237775, help_text='e.g. 1234567890', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_student_number', message='UofT Student number must be exactly 10 digits', regex='^\\d{10}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.CharField(choices=[(None, ''), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('22+', '22+')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='conduct_agree',
            field=models.BooleanField(help_text='I have read and agreed to the <a href="https://aws.amazon.com/codeofconduct/" rel="noopener noreferrer" target="_blank">AWS Code of Conduct</a>.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='discovery_method',
            field=models.TextField(choices=[(None, ''), ('instagram', 'Instagram'), ('in class/from a professor', 'In Class/From a professor'), ('discord', 'Discord'), ('email', 'Email'), ('from a friend', 'From a friend'), ('other', 'Other')], help_text='How did you hear about Hack the Student Life?', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='ethnicity',
            field=models.CharField(choices=[(None, ''), ('asian-indian', 'Asian Indian'), ('black-african-american', 'Black or African American'), ('chinese', 'Chinese'), ('filipino', 'Filipino'), ('guamanian-chamorro', 'Guamanian or Chamorro'), ('hispanic-latino', 'Hispanic/Latino/Spanish Origin'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('middle-eastern', 'Middle Eastern'), ('native-american', 'Native American or Alaskan Native'), ('native-hawaiian', 'Native Hawaiian'), ('samoan', 'Samoan'), ('vietnamese', 'Vietnamese'), ('caucasian', 'White / Caucasian'), ('other-asian', 'Other Asian (Thai, Cambodian, etc)'), ('other-pacific-islander', 'Other Pacific Islander'), ('other', 'Other (please specify)'), ('no-answer', 'Prefer not to answer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='program',
            field=models.CharField(choices=[(None, ''), ('chemical-engineering', 'Chemical Engineering'), ('civil-engineering', 'Civil Engineering'), ('computer-science', 'Computer Science'), ('electrical-engineering', 'Electrical Engineering'), ('engineering-science', 'Engineering Science'), ('industrial-engineering', 'Industrial Engineering'), ('materials-engineering', 'Materials Engineering'), ('mineral-engineering', 'Mineral Engineering'), ('track-one', 'TrackOne'), ('other', 'Other (please specify)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='sexual_orientation',
            field=models.CharField(choices=[(None, ''), ('straight', 'Heterosexual or straight'), ('gay-lesbian', 'Gay or lesbian'), ('bisexual', 'Bisexual'), ('different', 'Additional Identity not Listed (Please Specify)'), ('no-answer', 'Prefer not to answer')], help_text='Do you consider yourself to be any of the following?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='application',
            name='study_level',
            field=models.CharField(choices=[(None, ''), ('first-year', 'First Year'), ('second-year', 'Second Year'), ('third-year', 'Post Doctorate'), ('pey', 'PEY'), ('fourth-year', 'Fourth Year'), ('grad-school', 'Grad School')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='what_technical_experience',
            field=models.TextField(help_text='What is your technical experience with software and AWS?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='application',
            name='why_participate',
            field=models.TextField(help_text='Why do you want to participate in Hack the Student Life?', max_length=1000),
        ),
    ]
