# Generated by Django 3.2.15 on 2024-03-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0017_auto_20240301_1119"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="study_level",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("first-year", "First Year"),
                    ("second-year", "Second Year"),
                    ("third-year", "Third Year"),
                    ("pey", "PEY"),
                    ("fourth-year", "Fourth Year"),
                    ("grad-school", "Grad School"),
                ],
                max_length=50,
            ),
        ),
    ]
