# Generated by Django 3.2.15 on 2024-03-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0018_alter_application_study_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="ethnicity",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("asian-indian", "Asian Indian"),
                    ("black-african-american", "Black or African American"),
                    ("chinese", "Chinese"),
                    ("filipino", "Filipino"),
                    ("guamanian-chamorro", "Guamanian or Chamorro"),
                    ("hispanic-latino", "Hispanic/Latino/Spanish Origin"),
                    ("japanese", "Japanese"),
                    ("korean", "Korean"),
                    ("middle-eastern", "Middle Eastern"),
                    ("native-american", "Native American or Alaskan Native"),
                    ("native-hawaiian", "Native Hawaiian"),
                    ("samoan", "Samoan"),
                    ("vietnamese", "Vietnamese"),
                    ("caucasian", "White / Caucasian"),
                    ("other-asian", "Other Asian (Thai, Cambodian, etc)"),
                    ("other-pacific-islander", "Other Pacific Islander"),
                    ("other", "Other"),
                    ("no-answer", "Prefer not to answer"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="program",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("chemical-engineering", "Chemical Engineering"),
                    ("civil-engineering", "Civil Engineering"),
                    ("computer-science", "Computer Science"),
                    ("electrical-engineering", "Electrical Engineering"),
                    ("computer-engineering", "Computer Engineering"),
                    ("engineering-science", "Engineering Science"),
                    ("industrial-engineering", "Industrial Engineering"),
                    ("materials-engineering", "Materials Engineering"),
                    ("mineral-engineering", "Mineral Engineering"),
                    ("track-one", "TrackOne"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="sexual_orientation",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("straight", "Heterosexual or straight"),
                    ("gay-lesbian", "Gay or lesbian"),
                    ("bisexual", "Bisexual"),
                    ("different", "Additional Identity not Listed"),
                    ("no-answer", "Prefer not to answer"),
                ],
                help_text="Do you consider yourself to be any of the following?",
                max_length=1000,
            ),
        ),
    ]
