export const hackathonName = "AWS Hacks 2024";
export const adminGroup = "Hardware Site Admins";
export const minTeamSize = 2;
export const maxTeamSize = 4;
export const hardwareSignOutStartDate = new Date(2024, 2, 24, 8, 30);
export const hardwareSignOutEndDate = new Date(2024, 2, 24, 18, 0);
export const hssTestUserGroup = "HSS Test Users";
export const serverUrl = "https://hackstudentlife.ca/";
export const minProjectDescriptionLength = 60;
